version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 12
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
